# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/rprakashdass/Downloads/cmake-4.0.3-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/rprakashdass/Downloads/cmake-4.0.3-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rprakashdass/Downloads/Cpp-web-server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rprakashdass/Downloads/Cpp-web-server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/home/rprakashdass/Downloads/cmake-4.0.3-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/rprakashdass/Downloads/cmake-4.0.3-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/rprakashdass/Downloads/cmake-4.0.3-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/rprakashdass/Downloads/cmake-4.0.3-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/rprakashdass/Downloads/cmake-4.0.3-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/rprakashdass/Downloads/cmake-4.0.3-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/rprakashdass/Downloads/cmake-4.0.3-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/rprakashdass/Downloads/cmake-4.0.3-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rprakashdass/Downloads/Cpp-web-server/CMakeFiles /home/rprakashdass/Downloads/Cpp-web-server//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rprakashdass/Downloads/Cpp-web-server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lightcppframework

# Build rule for target.
lightcppframework: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lightcppframework
.PHONY : lightcppframework

# fast build rule for target.
lightcppframework/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/build
.PHONY : lightcppframework/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

src/ActionDispatcher.o: src/ActionDispatcher.cpp.o
.PHONY : src/ActionDispatcher.o

# target to build an object file
src/ActionDispatcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/ActionDispatcher.cpp.o
.PHONY : src/ActionDispatcher.cpp.o

src/ActionDispatcher.i: src/ActionDispatcher.cpp.i
.PHONY : src/ActionDispatcher.i

# target to preprocess a source file
src/ActionDispatcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/ActionDispatcher.cpp.i
.PHONY : src/ActionDispatcher.cpp.i

src/ActionDispatcher.s: src/ActionDispatcher.cpp.s
.PHONY : src/ActionDispatcher.s

# target to generate assembly for a file
src/ActionDispatcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/ActionDispatcher.cpp.s
.PHONY : src/ActionDispatcher.cpp.s

src/AppDispatcher.o: src/AppDispatcher.cpp.o
.PHONY : src/AppDispatcher.o

# target to build an object file
src/AppDispatcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/AppDispatcher.cpp.o
.PHONY : src/AppDispatcher.cpp.o

src/AppDispatcher.i: src/AppDispatcher.cpp.i
.PHONY : src/AppDispatcher.i

# target to preprocess a source file
src/AppDispatcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/AppDispatcher.cpp.i
.PHONY : src/AppDispatcher.cpp.i

src/AppDispatcher.s: src/AppDispatcher.cpp.s
.PHONY : src/AppDispatcher.s

# target to generate assembly for a file
src/AppDispatcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/AppDispatcher.cpp.s
.PHONY : src/AppDispatcher.cpp.s

src/HTTPRequest.o: src/HTTPRequest.cpp.o
.PHONY : src/HTTPRequest.o

# target to build an object file
src/HTTPRequest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/HTTPRequest.cpp.o
.PHONY : src/HTTPRequest.cpp.o

src/HTTPRequest.i: src/HTTPRequest.cpp.i
.PHONY : src/HTTPRequest.i

# target to preprocess a source file
src/HTTPRequest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/HTTPRequest.cpp.i
.PHONY : src/HTTPRequest.cpp.i

src/HTTPRequest.s: src/HTTPRequest.cpp.s
.PHONY : src/HTTPRequest.s

# target to generate assembly for a file
src/HTTPRequest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/HTTPRequest.cpp.s
.PHONY : src/HTTPRequest.cpp.s

src/HTTPResponse.o: src/HTTPResponse.cpp.o
.PHONY : src/HTTPResponse.o

# target to build an object file
src/HTTPResponse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/HTTPResponse.cpp.o
.PHONY : src/HTTPResponse.cpp.o

src/HTTPResponse.i: src/HTTPResponse.cpp.i
.PHONY : src/HTTPResponse.i

# target to preprocess a source file
src/HTTPResponse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/HTTPResponse.cpp.i
.PHONY : src/HTTPResponse.cpp.i

src/HTTPResponse.s: src/HTTPResponse.cpp.s
.PHONY : src/HTTPResponse.s

# target to generate assembly for a file
src/HTTPResponse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/HTTPResponse.cpp.s
.PHONY : src/HTTPResponse.cpp.s

src/Router.o: src/Router.cpp.o
.PHONY : src/Router.o

# target to build an object file
src/Router.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/Router.cpp.o
.PHONY : src/Router.cpp.o

src/Router.i: src/Router.cpp.i
.PHONY : src/Router.i

# target to preprocess a source file
src/Router.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/Router.cpp.i
.PHONY : src/Router.cpp.i

src/Router.s: src/Router.cpp.s
.PHONY : src/Router.s

# target to generate assembly for a file
src/Router.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/Router.cpp.s
.PHONY : src/Router.cpp.s

src/StaticServer.o: src/StaticServer.cpp.o
.PHONY : src/StaticServer.o

# target to build an object file
src/StaticServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/StaticServer.cpp.o
.PHONY : src/StaticServer.cpp.o

src/StaticServer.i: src/StaticServer.cpp.i
.PHONY : src/StaticServer.i

# target to preprocess a source file
src/StaticServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/StaticServer.cpp.i
.PHONY : src/StaticServer.cpp.i

src/StaticServer.s: src/StaticServer.cpp.s
.PHONY : src/StaticServer.s

# target to generate assembly for a file
src/StaticServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/StaticServer.cpp.s
.PHONY : src/StaticServer.cpp.s

src/ThreadPool.o: src/ThreadPool.cpp.o
.PHONY : src/ThreadPool.o

# target to build an object file
src/ThreadPool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/ThreadPool.cpp.o
.PHONY : src/ThreadPool.cpp.o

src/ThreadPool.i: src/ThreadPool.cpp.i
.PHONY : src/ThreadPool.i

# target to preprocess a source file
src/ThreadPool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/ThreadPool.cpp.i
.PHONY : src/ThreadPool.cpp.i

src/ThreadPool.s: src/ThreadPool.cpp.s
.PHONY : src/ThreadPool.s

# target to generate assembly for a file
src/ThreadPool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lightcppframework.dir/build.make CMakeFiles/lightcppframework.dir/src/ThreadPool.cpp.s
.PHONY : src/ThreadPool.cpp.s

src/server.o: src/server.cpp.o
.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... lightcppframework"
	@echo "... server"
	@echo "... src/ActionDispatcher.o"
	@echo "... src/ActionDispatcher.i"
	@echo "... src/ActionDispatcher.s"
	@echo "... src/AppDispatcher.o"
	@echo "... src/AppDispatcher.i"
	@echo "... src/AppDispatcher.s"
	@echo "... src/HTTPRequest.o"
	@echo "... src/HTTPRequest.i"
	@echo "... src/HTTPRequest.s"
	@echo "... src/HTTPResponse.o"
	@echo "... src/HTTPResponse.i"
	@echo "... src/HTTPResponse.s"
	@echo "... src/Router.o"
	@echo "... src/Router.i"
	@echo "... src/Router.s"
	@echo "... src/StaticServer.o"
	@echo "... src/StaticServer.i"
	@echo "... src/StaticServer.s"
	@echo "... src/ThreadPool.o"
	@echo "... src/ThreadPool.i"
	@echo "... src/ThreadPool.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

